### ISSUE TITLE
Integrate p5.js-svg library

### ISSUE THREAD

**Issue by caseywescott** [cienicera/p5.js-mint#1]
### Increasing Access

Add the p5.js-svg library to the project to enable SVG rendering in sketches.

### Feature enhancement details

Need to have p5.svg.js in project and in index.html
see -https://github.com/zenozeng/p5.js-svg
example: https://editor.p5js.org/dannyrozin/sketches/r1djoVow7

**Comment by ShantelPeters** [comment]
Hi @caseywescott can I be assigned to this issue please

**Comment by PedroCo3lho** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/nicera-labs).

### My background and how it can be leveraged
I'm a software developer, who worked in different projects contributing in a bunch of projects as a full-stack and blockchain programmer. I'm also graduating at Computer Science

### How I plan on tackling this issue
This enhancement can be handle by simply implementing the svg library in the project dependencies, and also implementing a functionality to test the feature, as in the issue #2

**Comment by BDCoy** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/nicera-labs).

### My background and how it can be leveraged
Hello, I’m Brayan. With over 3 years of experience in development, I am passionate about contributing to open-source projects and currently expanding my skill set with Rust, Cairo, and Solidity as part of my involvement with Dojo Coding. My recent role as a Full Stack Developer allowed me to specialize in a range of technologies including React, NextJs, Node.js, JavaScript, TypeScript, Docker, among many others. I am eager to apply my extensive experience and newly acquired skills to new challenges and innovative projects.


### How I plan on tackling this issue
To add the p5.js-svg library for SVG rendering in sketches, one should start by downloading the library from GitHub. The next step is to include the p5.svg.js script in the project directory and update the index.html file to reference this script. The script tag can be placed within the <head> or before the closing </body> tag. Once included, one can follow examples like the one provided here to implement SVG rendering in sketches. This will enable seamless creation and manipulation of SVG graphics using p5.js.

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/nicera-labs).

### My background and how it can be leveraged
I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, and Solidity. My journey with OnlyDust hackathons began at Edition 1, and I've since made 47 contributions across 11 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure.
I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges.
As we surf through Edition 7, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.

### How I plan on tackling this issue
I will approach solving this issue in the following steps:

1. Integration:
   - Add the p5.js-svg library to the project by including the script in the index.html file.
   - Use the latest version of p5.js-svg (currently 1.5.1) from a CDN or download it locally.

2. Configuration:
   - Modify the sketch setup to use SVG rendering by changing the createCanvas function call to include SVG as the third parameter.
   - Adjust any necessary stroke and fill settings to optimize for SVG output.

3. Implementation:
   - Create the desired sketch using p5.js drawing functions.
   - Ensure compatibility with SVG rendering by avoiding unsupported features or providing alternatives.

4. Export functionality:
   - Implement a mechanism to trigger SVG export, such as a button click or a specific function call.
   - Use the save() function provided by p5.js-svg to export the SVG file.

5. Testing:
   - Verify that the sketch renders correctly in SVG format.
   - Test the export functionality to ensure SVG files are generated and saved properly.

6. Documentation:
   - Update project documentation to include instructions on using SVG rendering and exporting.
   - Provide examples of SVG-specific considerations or optimizations.

This approach incorporates the key elements from the example provided, such as including the library, setting up the SVG canvas, and using the save function for export. It also considers the broader needs of integrating SVG capabilities into the project workflow.

**Comment by Ugo-X** [comment]
Thanks, will get to it.
