### ISSUE TITLE
Test SVG Generation and Export

### ISSUE THREAD

**Issue by caseywescott** [cienicera/p5.js-mint#11]
### Increasing Access

Testing the SVG generation and export functionality to ensure that the p5.js Web Editor correctly generates SVG files from user sketches and exports them without errors.

### Feature request details

This testing process will involve validating the accuracy and integrity of the generated SVGs, ensuring compatibility across different browsers and devices, and verifying that the export process works smoothly for various user scenarios. Proper testing ensures that users can reliably create and use SVGs for minting NFTs or other purposes.

**Tasks:**

**Create Test Cases for SVG Generation:**

Develop a set of test cases that cover a wide range of p5.js sketches, from simple shapes to complex animations and dynamic content.

Include test cases for sketches that use different p5.js functions, such as drawing primitives, text, transformations, and custom graphics.

Test the generation of multiple SVGs in sequence or based on different user inputs, ensuring that each SVG is accurately generated and distinct from the others.

**Verify SVG Output Integrity:**

Check the accuracy of the generated SVGs by comparing them to the expected output. Ensure that all elements, colors, and transformations are correctly rendered in the SVG.

Validate that the SVGs adhere to the correct SVG syntax and structure, with no missing or malformed tags or attributes.

Test SVGs for scalability and resolution independence, ensuring that they maintain visual quality when resized or viewed on different devices.

**Test SVG Export Functionality:**

Test the export process by saving the generated SVGs to the user’s local filesystem. Verify that the exported files are correctly named and stored in the desired location.

Ensure that the export function works consistently across different browsers, including Chrome, Firefox, Safari, and Edge, and on various operating systems (Windows, macOS, Linux).

Test exporting SVGs with various content sizes, from small icons to large, detailed images, and ensure the process handles all sizes without issues.

**Handle Multiple SVG Exports:**

Test the ability to export multiple SVGs generated in a single session. Ensure that all SVGs are correctly exported and stored as separate files.

Validate that the export function correctly handles user selections for exporting specific SVGs or exporting all generated SVGs at once.

Check the naming convention for multiple SVG exports, ensuring that filenames are unique and meaningful.
Test Edge Cases and Error Scenarios:

Test edge cases such as exporting an empty or partially generated SVG, handling invalid or unexpected input data, and exporting large files that might stress the system.

Ensure that the system gracefully handles errors during the export process, such as file system access issues, and provides appropriate feedback to the user.

Test scenarios where users interrupt the export process, such as closing the browser or navigating away from the page, and ensure the system handles these interruptions without data loss.

**Cross-Device and Cross-Browser Testing:**

Conduct tests on various devices, including desktops, tablets, and smartphones, to ensure the SVG generation and export functionality works consistently across different platforms.

Verify that the exported SVGs are viewable and editable in common vector graphic software, such as Adobe Illustrator, Inkscape, and browser-based SVG viewers.

**Performance Testing:**

Test the performance of the SVG generation and export processes, especially for complex or high-volume outputs. Ensure that the process is efficient and does not cause significant delays or resource usage spikes.

Monitor memory and CPU usage during the SVG generation and export processes, optimizing as necessary to prevent performance bottlenecks.

**Comment by zarah-s** [comment]
Can I hop on this?

**Comment by BenFaruna** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/nicera-labs).

### My background and how it can be leveraged
Hello, I am a software engineer with over 4 years of experience, with over 2 years writing JavaScript. I have had the opportunity to work with SVG creation in golang and solidity and I believe that knowledge will be helpful in understand the workflow and creating appropriate test cases.

### How I plan on tackling this issue
1. Understanding the workflow.
2. Make a written note highlighting critical areas of the code that should be extensively tested.
3. Write testcases and ensure they pass.
5. follow the instructions on the issue to test integrity of output, export functionalities, e.t.c.

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/nicera-labs).

### My background and how it can be leveraged
I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, and Solidity. My journey with OnlyDust hackathons began at Edition 1, and I've since made 47 contributions across 11 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure.
I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges.
As we surf through Edition 7, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.

### How I plan on tackling this issue
Understanding the Problem
The goal is to thoroughly test the SVG generation and export functionality in the p5.js Web Editor to ensure that users can reliably create and use SVGs for minting NFTs or other purposes. This involves validating the accuracy of generated SVGs, ensuring compatibility across different platforms, and verifying the smooth operation of the export process.
Proposed Solution
I will:
11. Create Comprehensive Test Cases:
• Develop a diverse set of test cases covering various p5.js sketch scenarios, including simple shapes, complex animations, and dynamic content.
• Ensure that the test cases test different p5.js functions, such as drawing primitives, text, transformations, and custom graphics.
• Include test cases for generating multiple SVGs in sequence or based on different user inputs.
12. Verify SVG Output Integrity:
• Compare generated SVGs to expected output to ensure accuracy of elements, colors, and transformations.
• Validate that SVGs adhere to correct SVG syntax and structure.
• Test SVGs for scalability and resolution independence.
13. Test SVG Export Functionality:
• Test exporting SVGs to the user's local filesystem, verifying correct naming and storage.
• Ensure compatibility across different browsers and operating systems.
• Test exporting various content sizes and handle multiple SVG exports.
• Check naming conventions for multiple SVG exports.
14. Handle Edge Cases and Error Scenarios:
• Test edge cases such as exporting empty or partially generated SVGs, handling invalid input data, and exporting large files.
• Ensure graceful handling of errors and provide appropriate feedback to the user.
• Test scenarios where users interrupt the export process.
15. Conduct Cross-Device and Cross-Browser Testing:
• Test on various devices and platforms to ensure consistent functionality.
• Verify compatibility with common vector graphic software.
16. Perform Performance Testing:
• Test the efficiency of SVG generation and export processes.
• Monitor resource usage and optimize as necessary to prevent performance bottlenecks.
By following these steps, I can comprehensively test the SVG generation and export functionality in the p5.js Web Editor, ensuring that users can reliably create and use SVGs for their intended purposes.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/nicera-labs).

### My background and how it can be leveraged
I have experience in frontend development and testing, including working with SVGs and web applications. I can effectively create comprehensive test cases for SVG generation and export functionality, ensuring accuracy, compatibility, and performance across different devices and browsers.

### How I plan on tackling this issue
1. **Develop Test Cases**: Create comprehensive tests for various p5.js sketches and functions, ensuring accurate SVG generation.
2. **Verify SVG Integrity**: Check SVG accuracy, syntax, and scalability.
3. **Test Export Functionality**: Validate the export process across different browsers and devices, and handle multiple exports.
4. **Handle Edge Cases**: Test error scenarios and system responses to interruptions.
5. **Cross-Device Testing**: Ensure compatibility across devices and software.
6. **Performance Monitoring**: Optimize and monitor resource usage during SVG generation and export.
