### ISSUE TITLE
Implement SVG export functionality

### ISSUE THREAD

**Issue by caseywescott** [cienicera/p5.js-mint#2]
### Increasing Access

Modify the save function to export the generated SVG instead of a PNG or JPEG.

### Feature enhancement details

This feature involves modifying the existing save function in the p5.js Web Editor to allow users to export their sketches as SVG files instead of the default PNG or JPEG formats. This is crucial for enabling the generation of vector graphics that can be further used for minting NFTs.

**Comment by Xaxxoo** [comment]
I'll love to work on this please.

**Comment by Bosun-Josh121** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/nicera-labs).

### My background and how it can be leveraged
Software engineering background with great experience in smart contract development with experience working on similar projects in previous od hacks(https://app.onlydust.com/u/Josh-121) looking forward to make a first contribution here

### How I plan on tackling this issue
I would go through the existing save function and make the changes to export the required svg. I would make all due corrections if necessary and would deliver swiftly

**Comment by PedroCo3lho** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/nicera-labs).

### My background and how it can be leveraged
I'm a software developer, who worked in different projects contributing to Starknet as a full-stack and blockchain programmer. I'm also graduating at Computer Science 

### How I plan on tackling this issue
Implementing a SVG library that will generate a SVG output of the p5 sketch and trigger it in the save functions to export the SVG

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/nicera-labs).

### My background and how it can be leveraged
I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, and Solidity. My journey with OnlyDust hackathons began at Edition 1, and I've since made 47 contributions across 11 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure.
I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges.
As we surf through Edition 7, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.

### How I plan on tackling this issue
I will approach this issue in the following steps:

1. Integration:
   - Incorporate the p5.js-svg library into the p5.js Web Editor environment.

2. Modification:
   - Adapt the existing save function to support SVG export.
   - Add an option or parameter to specify SVG as the desired output format.

3. Implementation:
   - Utilize the SVG rendering capabilities provided by p5.js-svg.
   - Implement the logic to capture the SVG content when the save function is called.

4. User Interface:
   - Update the editor's UI to include an option for SVG export in the save dialog or menu.

5. Testing:
   - Verify the SVG export functionality across various sketch types.
   - Ensure compatibility with existing PNG and JPEG export options.

6. Documentation:
   - Update the editor's documentation to explain the new SVG export feature.
   - Provide examples and use cases for SVG export, particularly in the context of NFT creation.

This approach leverages the capabilities of p5.js-svg to enable SVG export within the p5.js Web Editor, addressing the need for vector graphics output suitable for NFT minting and other applications requiring scalable graphics.

**Comment by Ugo-X** [comment]
Thanks, will get to it.
